name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_APP_API_KEY: ${{ secrets.VITE_APP_API_KEY }}
        run: npm run build

      - name: Configure Git
        run:
          git config --global user.email "tutos_aaf@hotmail.com"
          git config --global user.name "TutozGhub"

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
