name: Deploy React App to GitHub Pages

on:
  workflow_dispatch

jobs:
  build: 
    runs-on: ubuntu-latest
    
    env:
      VITE_APP_API_KEY: ${{ secrets.VITE_APP_API_KEY }}
      
    run: npm run build
